services:
  backend:
    build: ./backend
    container_name: nexttrack_backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /Volumes/MatthewSSD/nexttrack_data/MillionSongSubset:/data/msd:ro
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: nexttrack_db

    env_file:
      - .env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: