# Generated by Django 5.1.1 on 2026-05-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
    ]
