# Generated by Django 5.1.1 on 2026-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_album_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musicbrainz_release_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='musicbrainz_artist_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='msd_song_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='msd_track_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
