# Generated by Django 5.1.1 on 2026-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_album_musicbrainz_release_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedTrackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MSD', 'Million Song Dataset'), ('MUSICBRAINZ', 'MusicBrainz')], max_length=50)),
                ('source_track_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_song_id', models.CharField(blank=True, max_length=100, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=255)),
                ('artist_mbid', models.CharField(blank=True, max_length=100)),
                ('album_name', models.CharField(blank=True, max_length=255)),
                ('track_name', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source'], name='recommendat_source_8ee0bb_idx'), models.Index(fields=['processed'], name='recommendat_process_8f18fa_idx'), models.Index(fields=['source_track_id'], name='recommendat_source__2552f1_idx')],
            },
        ),
    ]
