# Generated by Django 5.1.1 on 2026-05-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_importedtrackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrototypeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_relevance', models.PositiveSmallIntegerField()),
                ('explanation_clarity', models.PositiveSmallIntegerField()),
                ('interface_ease_of_use', models.PositiveSmallIntegerField()),
                ('search_clarity', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.session')),
            ],
        ),
    ]
