# Generated by Django 5.1.1 on 2026-07-15 11:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_prototypefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('genre', 'Genre'), ('mood', 'Mood'), ('era', 'Era'), ('context', 'Listening context'), ('other', 'Other')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('source', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['artist__artist_name', 'album_name']},
        ),
        migrations.AlterModelOptions(
            name='importedtrackdata',
            options={'ordering': ['-imported_at']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['artist__artist_name', 'track_name']},
        ),
        migrations.RemoveIndex(
            model_name='importedtrackdata',
            name='recommendat_source_8ee0bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='importedtrackdata',
            name='recommendat_process_8f18fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='importedtrackdata',
            name='recommendat_source__2552f1_idx',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='musicbrainz_release_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedtrackdata',
            name='album_mbid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='importedtrackdata',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedtrackdata',
            name='recording_mbid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='importedtrackdata',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='track',
            name='enrichment_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('ambiguous', 'Ambiguous'), ('not_found', 'Not found'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='familiarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='loudness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='musicbrainz_recording_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='track',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='musicbrainz_release_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='musicbrainz_artist_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='importedtrackdata',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='importedtrackdata',
            name='source',
            field=models.CharField(choices=[('msd', 'Million Song Dataset'), ('lastfm', 'Last.fm Dataset'), ('musicbrainz', 'MusicBrainz'), ('cover_art', 'Cover Art Archive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prototypefeedback',
            name='explanation_clarity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='prototypefeedback',
            name='interface_ease_of_use',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='prototypefeedback',
            name='recommendation_relevance',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='prototypefeedback',
            name='search_clarity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='energy_pref',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='popularity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='tempo_pref',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='msd_song_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='importedtrackdata',
            index=models.Index(fields=['source', 'source_track_id'], name='import_source_track_idx'),
        ),
        migrations.AddIndex(
            model_name='importedtrackdata',
            index=models.Index(fields=['artist_name', 'track_name'], name='import_artist_track_idx'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('artist', 'album_name'), name='unique_album_per_artist'),
        ),
        migrations.AddConstraint(
            model_name='importedtrackdata',
            constraint=models.UniqueConstraint(fields=('source', 'source_track_id'), name='unique_imported_source_track'),
        ),
        migrations.AddConstraint(
            model_name='recommendationresult',
            constraint=models.UniqueConstraint(fields=('session', 'track'), name='unique_recommendation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='sessiontrack',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_position_per_session'),
        ),
        migrations.AddConstraint(
            model_name='sessiontrack',
            constraint=models.UniqueConstraint(fields=('session', 'track'), name='unique_track_per_session'),
        ),
        migrations.AddField(
            model_name='tracktag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tags', to='recommendations.tag'),
        ),
        migrations.AddField(
            model_name='tracktag',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tags', to='recommendations.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tracks', through='recommendations.TrackTag', to='recommendations.tag'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist', 'track_name'], name='track_artist_name_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['genre', 'energy'], name='track_genre_energy_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['tempo'], name='track_tempo_idx'),
        ),
        migrations.AddConstraint(
            model_name='tracktag',
            constraint=models.UniqueConstraint(fields=('track', 'tag'), name='unique_tag_per_track'),
        ),
    ]
