# Generated by Django 5.1.1 on 2026-09-05 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_track_key_track_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototypefeedback',
            name='recommendation_relevance',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
