# Generated by Django 5.1.1 on 2026-09-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_alter_prototypefeedback_recommendation_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypefeedback',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
